kmodules/client-go

Gopkg.lock
Gopkg.toml
apps/v1beta1/deployment.go
apps/v1beta1/statefulset.go
core/v1/configmap.go
core/v1/rc.go
core/v1/secret.go
core/v1/service.go
core/v1/serviceaccount.go
extensions/v1beta1/daemonset.go
extensions/v1beta1/deployment.go
extensions/v1beta1/replicaset.go
rbac/v1beta1/role.go
rbac/v1beta1/rolebinding.go

Our forked version fixes array comparison bug: https://github.com/mattbaird/jsonpatch/issues/7

Switch jsonpatch library to our forked version.

---

apps/v1beta1/deployment.go
apps/v1beta1/statefulset.go
core/v1/configmap.go
core/v1/rc.go
core/v1/secret.go
core/v1/service.go
core/v1/serviceaccount.go
extensions/v1beta1/daemonset.go
extensions/v1beta1/deployment.go
extensions/v1beta1/replicaset.go
kubedb/v1alpha1/dormant_database.go
kubedb/v1alpha1/elasticsearch.go
kubedb/v1alpha1/postgres.go
kubedb/v1alpha1/snapshot.go
rbac/v1beta1/role.go
rbac/v1beta1/rolebinding.go
searchlight/v1alpha1/cluster_alert.go
searchlight/v1alpha1/node_alert.go
searchlight/v1alpha1/pod_alert.go

- Poll Immediately.
- Ensure retry on errors other than NotFound.
- Return false, error for NotFound.

Fix Poll-ing

---

Gopkg.lock
certificate/v1beta1/csr.go
certificate/v1beta1/kubernetes.go

https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

Add CertificateSigningRequest

---

Gopkg.lock
apps/v1beta1/deployment.go
apps/v1beta1/statefulset.go
certificates/v1beta1/csr.go
core/v1/configmap.go
core/v1/rc.go
core/v1/secret.go
core/v1/service.go
core/v1/serviceaccount.go
extensions/v1beta1/daemonset.go
extensions/v1beta1/deployment.go
extensions/v1beta1/replicaset.go
kubedb/v1alpha1/dormant_database.go
kubedb/v1alpha1/elasticsearch.go
kubedb/v1alpha1/postgres.go
kubedb/v1alpha1/snapshot.go
rbac/v1beta1/role.go
rbac/v1beta1/rolebinding.go
searchlight/v1alpha1/cluster_alert.go
searchlight/v1alpha1/node_alert.go
searchlight/v1alpha1/pod_alert.go

eg: https://github.com/kelseyhightower/kubernetes-initializer-tutorial/blob/2645c93e05f281c251ae7d835c7bb93dfdded0b8/envoy-initializer/main.go#L179

Use StrategicMergePatch

---

Gopkg.lock
kubedb/v1alpha1/dormant_database.go
kubedb/v1alpha1/elasticsearch.go
kubedb/v1alpha1/postgres.go
kubedb/v1alpha1/snapshot.go
searchlight/v1alpha1/cluster_alert.go
searchlight/v1alpha1/node_alert.go
searchlight/v1alpha1/pod_alert.go
stash/v1alpha1/restic.go
voyager/v1beta1/certificate.go
voyager/v1beta1/ingress.go

- https://github.com/kubernetes/kubernetes/issues/52772
- https://github.com/kubernetes/kubernetes/pull/40096/files
- https://github.com/kubernetes/apimachinery/blob/1168e538ea3ccf444854d1fdd5681d2d876680a7/pkg/util/jsonmergepatch/patch.go#L28

Use json merge patch for CRDs.

---

Gopkg.lock
backup_manager.go

This used to live in appctl, kubed and pharmer repo.

Move BackupManager to kutil

---

core/v1/node.go

Node.Status.Phase is deprecated

Fix NodeReady

---

Gopkg.lock
tools/queue/README.md
tools/queue/worker.go

ref: https://github.com/kubernetes-incubator/apiserver-builder/tree/master/pkg/controller

Add Workqueue tools from apiserver-builder

---

discovery/restmapper.go
meta/lib.go

ref: https://github.com/kubernetes/apimachinery/blob/bfe7139b14565386b4470736ca765bf21616b60e/pkg/api/meta/restmapper.go#L72

Add RestMapper

---

Gopkg.lock
Gopkg.toml
tools/plugin_installer/install.go

Example usage: https://github.com/tamalsaha/kubectl-plugin-demo

Add installer command for cobra based clis

---

tools/clientcmd/client_config.go

https://github.com/appscode/kutil/pull/110

Use InClustrConfig only if incluster

---

Gopkg.lock
apiextensions/v1beta1/README.md
apiextensions/v1beta1/cli-utils.go
apiextensions/v1beta1/convert_types.go
apiextensions/v1beta1/crdvalidation.go
apiextensions/v1beta1/crdvalidation_test.go

Fork ant31/crd-validation

---

apiextensions/v1beta1/kubernetes.go

This will be required to add openapi spec to existing CRDs

Update registered CRD

---

tools/queue/handler.go

@the-redback , we can use this in kubedb

Add filteredEventHandler

---

tools/analytics/analytics.go

https://github.com/kubernetes/kubernetes/commit/0f5013b71532560f0ea0417346fb99f8db1f7fde

Use /sys/class/dmi/id to detect GKE

---

Gopkg.lock
Gopkg.toml
tools/docker/lib.go

https://github.com/tamalsaha/docker-image-puller

Add docker tools

---

apiextensions/v1beta1/cli-utils.go
apiextensions/v1beta1/kubernetes.go

- https://blog.openshift.com/kubernetes-custom-resources-grow-up-in-v1-10/
- https://twitter.com/tsaha/status/992117278576492544

Enable status sub resource for CRDs.

---

Gopkg.lock
tools/doctor/doctor.go
tools/doctor/extended_apiserver.go
tools/doctor/kube_ca.go
tools/doctor/master_args.go
tools/doctor/pod_args.go
tools/doctor/types.go
tools/doctor/version.go

ref: https://github.com/tamalsaha/kube-doctor

Add Kubernetes diagnostic tool

---

core/v1/secret.go

secret type can't be modified once created, so we have to delete first, then recreate with correct type

Support syncing secret type in CreateOrPatchSecret

---

tools/doctor/pod_args.go

https://github.com/kubepack/onessl/issues/35

Fix kube-apiserver pod arg parsing for kops clusters

---

tools/doctor/kube_proxy.go
tools/doctor/master_args.go
tools/doctor/types.go

ref: https://github.com/kubepack/onessl/issues/33

Check kube-proxy running on master instances

---

apiextensions/v1beta1/cli-utils.go

xref: https://github.com/ant31/crd-validation/pull/5

Ensure crd status is not rendered

---

core/v1/kubernetes.go
discovery/restmapper_test.go
openapi/render.go

Perform stable merge of LocalObjectReference

---

apiextensions/v1beta1/cli-utils.go

Support categories in CRDs

---

meta/cmp.go

Ski[ `kubectl/last-applied-configuration` from length comparison

---

meta/cmp.go

Use lastAppliedConfiguration const everywhere

---

meta/lib.go
meta/lib_test.go

Add FilterKeys

---

meta/arguments.go
meta/arguments_test.go

Allow protected flags in UpsertArgumentList method

---

meta/hash.go

Ignore last-applied-configuration from GenerationHash

---

Gopkg.lock
meta/hash.go
tools/queue/handler.go

Add NewObservableHandler

---

meta/hash.go
tools/queue/handler.go

Refactor AlreadyObserved method

---

meta/cmp.go
meta/hash.go

Make LastAppliedConfigAnnotation public

---

Gopkg.lock
meta/hash.go

Use IntHash in AlreadyObserved helpers

---

meta/hash.go

panic on error in AlreadyObserved

---

apiextensions/v1beta1/crdvalidation.go

Fix IntHash openapi v3 schema

---

tools/certstore/lib.go

SetCA from []byte in CertStore

---

tools/certstore/lib.go

Introduce CertPair() and CertPairBytes() methods for CertStore

---

tools/certstore/lib.go

Support SANS for client cert

---

tools/certstore/lib.go

xref: https://tip.golang.org/doc/go1.11#crypto/x509

Automatically add Cn to SANS DNS names

---

meta/hash.go

Correctly generate IntHash for new object in AlreadyObserved2

---

tools/certstore/lib.go

xref: https://tip.golang.org/doc/go1.11#crypto/x509

Remove CommonName from CertStore

---

dynamic/unstructured.go

Wrap methods in dynamic pkg

---

dynamic/kubernetes.go

Add generic Ensure|Remove owner ref by name list

---

meta/patch.go

Use interface{} to generate patch

---

dynamic/kubernetes.go

Ignore NotFound errors

---

Gopkg.lock
admissionregistration/v1beta1/kubernetes.go
admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go

Add patch utils for webhooks

---

admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go
tools/watch/informerwatcher.go
tools/watch/until_test.go

Cleanup patch util for webhooks

---

Gopkg.lock
admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go
util.go

Add (Update | Sync)UpdateMutatingWebhookCABundle helper methods

---

admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go

Remove debug printlns

---

Gopkg.lock
core/v1/serviceaccount.go
tools/controller/README.md
tools/controller/client_builder.go
tools/controller/controller_ref_manager.go
tools/controller/controller_ref_manager_test.go
tools/controller/controller_utils.go
tools/controller/controller_utils_test.go
tools/controller/doc.go

Fork ClientBuilder from k8s.io/kubernetes/pkg/controller

---

Gopkg.lock
Gopkg.toml
discovery/lib.go
discovery/lib_test.go
discovery/restmapper_test.go

Add Kubernetes version checker

---

discovery/lib.go
discovery/lib_test.go

Make version constraint / blacklist public

---

meta/cloud.go
meta/incluster.go
tools/analytics/analytics.go
tools/clientcmd/client_config.go

Fix ClientConfig and AnalyticsID for AKS

---

tools/clientcmd/client_config.go

Make FixAKS public

---

tools/clientcmd/client_config.go

Simplify FixAKS logic

---

tools/clientcmd/client_config.go

Add --use-kubeapiserver-fqdn-for-aks flag to AKS fix

---

admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go
admissionregistration/v1beta1/xray.go
discovery/lib.go
discovery/restmapper.go

Because it is damn time that we detect webhooks are actually activated.

Add WebhookXray

---

Gopkg.lock
admissionregistration/v1beta1/xray.go
hack/make.py

Various cleanup for webhook xray

---

admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go

Remove extra delays as webhook.

---

admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go
admissionregistration/v1beta1/xray.go

Use UntilWithSync to test webhook

---

discovery/restmapper.go
dynamic/kubernetes.go

Add DetectWorkload helper

---

discovery/restmapper.go
dynamic/kubernetes.go

Fix ResourceForGVK() helper

---

admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go
admissionregistration/v1beta1/xray.go
dynamic/kubernetes.go

Add HasLabel and HasAnnotation helpers

---

admissionregistration/v1beta1/xray.go

Add admission-webhooks.appscode.com/activated annotation to webhookconfig

---

admissionregistration/v1beta1/xray.go
dynamic/kubernetes.go

Return key values for UntilHasLabel helpers

---

dynamic/kubernetes.go

Use Unstructured type for UntilHasLabel helpers

---

admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go
admissionregistration/v1beta1/xray.go
dynamic/kubernetes.go

Apply various fixes to webhook xray

---

admissionregistration/v1beta1/xray.go
apiregistration/v1beta1/apiservice.go
apiregistration/v1beta1/kubernetes.go

Wait until apiservice pods are ready

---

admissionregistration/v1beta1/mutatingwebhookconfiguration.go
admissionregistration/v1beta1/validatingwebhookconfiguration.go
admissionregistration/v1beta1/xray.go

https://github.com/kubernetes/apiserver/blob/kubernetes-1.12.0/pkg/util/webhook/error.go

Retry on ErrCallingWebhook in xray

---

admissionregistration/v1beta1/xray.go
discovery/restmapper_test.go
openapi/render.go

Recognize denied request by any webhook in xray

---

tools/queue/handler.go

Add NewObservableUpdateHandler

---

admissionregistration/v1beta1/xray.go
util.go

Make AdmissionWebhookDeniedRequest public

---

meta/hash.go

Fix observation comparison for AlreadyObserved2

---

Gopkg.lock
tools/cli/cli.go

Add analytics tools for cli

---

admissionregistration/v1beta1/xray.go
dynamic/kubernetes.go

Wait until deletion is completed in xray

---

Gopkg.lock
apiextensions/v1beta1/cli-utils.go
meta/cloud.go
tools/backup/manager.go
tools/doctor/types.go

Use sigs.k8s.io/yaml

---

Gopkg.lock
meta/encoding.go

Add resource.Quantity aware mapstructure.Decode util

---

admissionregistration/v1beta1/xray.go

Fixes https://github.com/appscode/kutil/issues/286

Update webhook error message format for Kubernetes 1.13+

---

discovery/lib.go

Log k8s version in version checker

---

tools/clusterid/lib.go

Add cluster id tool

---

tools/doctor/pod_args.go
tools/exec/lib.go

xref: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

Support functional options for exec tools

---

discovery/restmapper.go

Use TypeAccessor to detect GroupVersionKind

---

discovery/restmapper.go

Add APIResourceForGVK helper

---

Gopkg.lock
Gopkg.toml
openapi/render.go

Update Kubernetes client libraries to 1.13.0

---

logs/logs.go

xref: https://github.com/kubernetes/kubernetes/issues/74560

Add klog compatible logs pkg

---

meta/lib.go

xref: https://github.com/kubedb/project/issues/370

Avoid propagating app.kubernetes.io/* labels to offshoots

---

meta/lib.go

Propagate app.kubernetes.io/part-of key from crd to offshoots

---

Gopkg.lock
Gopkg.toml
tools/clientcmd/client_getter.go

Add RestClientGetter factory methods

---

meta/lib.go

Rename InitFlags to AddLabelBlacklistFlag

---

core/v1/kubernetes.go

Add IsOwnedBy helpers

---

openapi/render.go

Fix openapi spec generation for multi-version apis

---

meta/hash.go
tools/queue/handler.go

Add NewReconcilableHandler

---

go.mod
go.sum
meta/hash.go
vendor/github.com/appscode/go/encoding/json/types/int_hash.go
vendor/modules.txt

Only match generation for AlreadyReconciled() helper

---

dynamic/unstructured.go

Add dynamic UpdateStatus() helper

---

go.mod
go.sum
tools/probe/doc.go
tools/probe/exec/exec.go
tools/probe/exec/exec_test.go
tools/probe/exec/ioutils.go
tools/probe/exec/ioutils_test.go
tools/probe/http/http.go
tools/probe/http/http_test.go
tools/probe/probe.go
tools/probe/tcp/tcp.go
tools/probe/tcp/tcp_test.go
vendor/github.com/stretchr/testify/require/doc.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require.go.tmpl
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
vendor/github.com/stretchr/testify/require/requirements.go
vendor/k8s.io/utils/exec/doc.go
vendor/k8s.io/utils/exec/exec.go
vendor/k8s.io/utils/io/read.go
vendor/modules.txt

xref: https://github.com/kubernetes/kubernetes/blob/9790262f128aa9d27733dac46619af1d18459439/pkg/probe/doc.go#L18

Copy probe pkg from k8s.io/kubernetes/pkg/probe

---

logs/logs.go

Fix klog Parsing

---

discovery/lib.go

Blacklist Kubernetes 1.16.0 and 1.16.1

---

core/v1/kubernetes.go

Change EnsureOwnerReference helper

---

meta/hash.go
tools/queue/handler.go

Remove deprecated functions

---

core/v1/node.go
meta/annotations.go

Add Topology() helper

---

apiextensions/v1beta1/kubernetes.go
discovery/lib.go

Register CRDs for Kubernetes 1.11

---

meta/hash.go
tools/queue/handler.go

Print better error messages for AlreadyReconciled

---

core/v1/node.go

Add labels to DetectTopology

---

tools/wait/wait.go
tools/wait/wait_test.go
vendor/k8s.io/client-go/dynamic/fake/simple.go
vendor/k8s.io/client-go/testing/actions.go
vendor/k8s.io/client-go/testing/fake.go
vendor/k8s.io/client-go/testing/fixture.go
vendor/modules.txt

Add library for doing `kubectl wait`

---

discovery/lib.go

Add ExistsGroupKind

---

.github/workflows/ci.yml
api/v1/conditions.go

Add list of common condition types

---

networking/v1beta1/ingress.go
networking/v1beta1/kubernetes.go

Add networking/v1beta1 Ingress helper

---

apiextensions/kubernetes.go

Remove defaults from crd v1beta1

---

meta/lib.go
meta/lib_test.go

Add NameWithSuffix helper

---

tools/clientcmd/client_getter.go
vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
vendor/modules.txt

Use in-memory cache for Discovery client

---

dynamic/kubernetes.go

Add ResourceExists helpers

---

core/v1/node.go
vendor/k8s.io/client-go/metadata/interface.go
vendor/k8s.io/client-go/metadata/metadata.go
vendor/modules.txt

Detect cluster topology from node labels not annotations

---

core/v1/node.go

Simplify cluster topology detector

---

api/v1/certificates.go

Signed-off-by: kamolhasan <kamol@appscode.com>

Add certificate helper method for overwriting secretName

---

core/v1/kubernetes.go

Add GetControllerWithGroupKind helper

---

core/v1/kubernetes.go

Add helper IsOwnerOfGroupKind

---

api/v1/certificates.go
api/v1/generated.proto
api/v1/openapi_generated.go

Signed-off-by: kamolhasan <kamol@appscode.com>

Make TLSConfig.IssuerRef optional

---

tools/clusterid/lib.go

Add ClusterUID helper

---

api/v1/certificate_test.go
api/v1/certificates.go
api/v1/openapi_generated.go

Add SetMissingSpecForCertificate helper

---

meta/incluster.go

Signed-off-by: Mohammad Fahim Abrar <fahimabrar@appscode.com>

Add `ClusterDomain` Function

---

tools/certholder/lib.go

Add cert holder

---

core/v1/kubernetes.go

Add IsOwnerOfGroup

---

tools/queue/handler.go
tools/queue/handler_test.go

Add status aware NewChangeHandler

---

dynamic/conditions/conditions.go
dynamic/conditions/conditions_test.go
go.sum
tools/queue/handler_test.go

Signed-off-by: Emruz Hossain <emruz@appscode.com>

Add condition helpers using dynamic client

---

apps/v1/deployment.go
apps/v1/statefulset.go

Add Is***Ready helpers

---

api/v1/conditions.go

Only update if the new condition is based on later observed generation

---

core/v1/service.go

Merge service ports by name

---

core/v1/kubernetes.go

Allow emptying Command, Args & Env for container

---

tools/queue/handler.go

Invoke update handler on labels or annotations change

---

tools/queue/handler.go

Add NewSpecStatusChangeHandler

---

core/v1/pod_status.go
tools/portforward/tunnel_test.go

Add pod status condition helpers

---

tools/parser/parser.go

Add parser helper to load a directory of YAML files

---

core/v1/pod.go

Add IsPodReady helper

---

core/v1/kubernetes.go

Allow emptying VolumeMounts for container

---

meta/ipv6.go

Add IPv6Enabled

---

meta/ipv6.go

Signed-off-by: Mohammad Fahim Abrar <fahimabrar@appscode.com>

Add `IPv6EnabledInKernel`

---

dynamic/factory/README.md
dynamic/factory/cached.go
dynamic/factory/direct.go
dynamic/factory/interface.go
meta/dataformat.go
meta/ipv6.go
tools/converter/lib.go
tools/parser/parser.go
vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go
vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go
vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go
vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go
vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go
vendor/modules.txt

Add dynamic factory

---

discovery/lib.go

Signed-off-by: kamolhasan <kamol@appscode.com>

Remove intermediate logs while discovering objects

---

go.mod
tools/clientcache/README.md
tools/clientcache/lib.go

Add clientcache package

---

discovery/restmapper.go

Introduce ResourceMapper interface

---

discovery/restmapper.go

Add Exists{GVR, GVK} to ResourceMapper

---

discovery/restmapper.go

Add ResourceIDFor*** helpers to ResourceMapper

---

discovery/restmapper.go

Add Reset method to ResourceMapper

---

core/v1/kubernetes.go
core/v1/kubernetes_test.go
go.mod
go.sum
vendor/gomodules.xyz/mergo/.deepsource.toml
vendor/gomodules.xyz/mergo/.gitignore
vendor/gomodules.xyz/mergo/CODE_OF_CONDUCT.md
vendor/gomodules.xyz/mergo/LICENSE
vendor/gomodules.xyz/mergo/README.md
vendor/gomodules.xyz/mergo/doc.go
vendor/gomodules.xyz/mergo/go.mod
vendor/gomodules.xyz/mergo/go.sum
vendor/gomodules.xyz/mergo/map.go
vendor/gomodules.xyz/mergo/merge.go
vendor/gomodules.xyz/mergo/mergo.go
vendor/modules.txt

Fix repetitive patch-ing

---

admissionregistration/v1/kubernetes.go
admissionregistration/v1/mutatingwebhookconfiguration.go
admissionregistration/v1/validatingwebhookconfiguration.go
admissionregistration/v1/xray.go
apiregistration/v1/apiservice.go
apiregistration/v1/kubernetes.go

Add apiservice and webhook v1 utils

---

core/v1/kubernetes.go

Always default env fieldRef APIVersion to v1

---

go.sum
tools/queue/handler.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/codec.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/doc.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/dryrun.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/metadata_client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/namespaced_client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/object.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/watch.go
vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
vendor/sigs.k8s.io/controller-runtime/pkg/log/null.go
vendor/sigs.k8s.io/controller-runtime/pkg/log/warning_handler.go

Support only watching default namespace

---

tools/queue/handler.go

Support restricting to a custom namespace

---

tools/queue/handler.go

Don't restrict cluster scoped objects to a namespace

---

tools/parser/parser.go

List resources from dir or FS

---

tools/configreader/cached.go
tools/configreader/configmap.go
tools/configreader/direct.go
tools/configreader/interface.go
tools/configreader/secret.go

Add configreader

---

tools/queue/handler.go

Only log community edition warning for appscode crds by default

---

tools/exec/lib.go

Check for running container before executing command

---

tools/exec/lib.go

Correctly check for running container

---

tools/queue/handler.go

Detect GVK via scheme

---

tools/parser/parser.go

Track filename when processing directory

---

Makefile
meta/lib.go

Improve Filter/Overwrite/Merge Keys helpers

---

tools/clientcmd/client_getter.go

Return dynamic rest mapper

---

core/v1/kubernetes.go
meta/lib.go

Support multiple input maps for OverwriteKeys

---

meta/preconditions.go

Add PreConditionSet

---

Makefile
client/client.go

Inform create/patch op in TransformFunc method

---

openapi/util.go

Add GetDefinitions helper

---

tools/queue/worker.go

Automatically recover from panic in reconcilers

---

client/client.go

Signed-off-by: Rakibul-Hossain <rakibul.hossain@appscode.com>

Add PatchStatus function

---

batch/v1/cronjob.go

Signed-off-by: piyush1146115 <piyush@appscode.com>

Add Cronjob to batch/v1.

---

apiextensions/kubernetes.go

Detect crd readiness using crd status.conditions

---

api/v1/object.go

Move EdgeLabel from resource-metadata

---

client/client.go

Signed-off-by: Pulak Kanti Bhowmick <pulak@appscode.com>

Pass context in function parameters

---

api/v1/resource.go

ExtractResourceID

---

client/apiutil/cachable.go
client/apiutil/dynamic.go
client/delegated.go
go.mod
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/doc.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/metadata_infomer_wrapper.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/selector.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
vendor/sigs.k8s.io/controller-runtime/pkg/internal/log/log.go
vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go

Correctly detect whether any api type is cachable

---

api/v1/conditions.go

Signed-off-by: piyush1146115 <piyush@appscode.com>

Add a function for checking if the condition is in unknown state.

---

go.mod
go.sum
vendor/modules.txt

Signed-off-by: 1gtm <1gtm@appscode.com>

Fix satori/go.uuid security vulnerability

---

api/v1/object.go

Add ObjectIDMap

---

api/v1/timeofday.go

Signed-off-by: Pulak Kanti Bhowmick <pulak@appscode.com>

Add location based time function

---

meta/incluster.go

Add PodName & PodNamespace helpers

---

core/v1/kubernetes.go

Preserve container TerminationMessagePath & TerminationMessagePolicy

---

dynamic/conditions/conditions.go

Signed-off-by: kamolhasan <kamol@appscode.com>

Add support for updateConditions method in dynamic client

---

policy/pdb.go
policy/v1beta1/kubernetes.go
policy/v1beta1/pdb.go

Support PDB v1 or v1beta1 api based on k8s version

---

api/v1/object.go

Add edge labels ops & recommended_for

---

batch/batch.go
batch/v1beta1/cronjob.go
batch/v1beta1/kubernetes.go

Add CronJob version-aware helper

---

meta/cloud.go
meta/incluster.go
meta/ipv6.go
tools/backup/manager.go
tools/certholder/lib.go
tools/doctor/kube_ca.go
tools/parser/parser.go
tools/portforward/tunnel.go
tools/wait/wait_test.go

Fix linter warning

---

discovery/lib.go

Fake clients can work with ServerGroupsAndResources

Use discovery.ServerGroupsAndResources for discovery apis

---

batch/batch.go
policy/pdb.go

Handle status conversion for batch & policy types

---

batch/batch.go
policy/pdb.go

Add generic PatchCronJob

---

batch/batch.go
discovery/lib.go
go.mod
go.sum
policy/pdb.go
vendor/gomodules.xyz/sync/LICENSE
vendor/gomodules.xyz/sync/README.md
vendor/gomodules.xyz/sync/once.go
vendor/kmodules.xyz/apiversion/.gitignore
vendor/kmodules.xyz/apiversion/LICENSE
vendor/kmodules.xyz/apiversion/README.md
vendor/kmodules.xyz/apiversion/lib.go
vendor/modules.txt

Check for CronJob/PDB version only once

---

client/duck/controller.go
client/duck/reconciler.go

Inject proper client into duck reconciler

---

client/duck/controller.go

Create client for each duck controller

---

policy/pdb.go

Signed-off-by: Arnob kumar saha <arnob@appscode.com>

Add `DeletePodDisruptionBudgets` utility

---

policy/evict.go

Add version aware EvictPod api

---

client/duck/unstructured_client.go

Detect GVK correctly for duck client

---

client/apiutil/pods.go

Fix CollectPullSecrets

---

client/apiutil/pods.go
client/apiutil/pods_test.go

Ignore KIND loaded image's imageID

---

client/apiutil/pods.go
client/apiutil/pods_test.go

Ignore missing container status in GetImageRef

---

policy/evict.go
policy/pdb.go

Fix Eviction version detection

---

client/apiutil/pods.go

Add option to skip full lineage

---

client/client.go

Signed-off-by: Pulak Kanti Bhowmick <pulak@appscode.com>

Avoid strategic merge patch for unstructured object

---

api/v1/resource.go

Optimize ExtractResourceID if input already resourceID

---

go.mod
go.sum
meta/incluster.go
vendor/github.com/google/go-containerregistry/pkg/name/errors.go
vendor/github.com/google/go-containerregistry/pkg/name/ref.go
vendor/modules.txt

Add helper methods for pod node name and service account

---

client/client.go

Signed-off-by: Masudur Rahman <masud@appscode.com>

CreateOrPatch: Set Elem() value if data is of pointer type

---

api/v1/object.go
api/v1/object_enum.go

Signed-off-by: Rokibul Hasan <mdrokibulhasan@appscode.com>

Add ocm_bind, placed_into edge label.

---

api/v1/object.go
api/v1/object_enum.go

Signed-off-by: Rokibul Hasan <mdrokibulhasan@appscode.com>

Add auth_secret edge label.

---

.github/workflows/ci.yml
Makefile
apiextensions/controller.go
conditions/getter.go
conditions/merge.go
meta/preconditions.go
tools/portforward/tunnel.go

Signed-off-by: 1gtm <1gtm@appscode.com>

Use Go 1.23
